# Generated by Django 3.2 on 2021-04-10 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='book',
            table='book_info',
        ),
    ]
